### ISSUE TITLE
Feature Suggestion: File Upload

### ISSUE THREAD

**Issue by nnnnathann** [there4/slim-test-helpers#26]
Hi, thanks for the library.

Thoughts on implementing $_FILES superglobal testing?

**Comment by craig-davis** [comment]
I've never had need for it, but I can see the usefulness of it. I might argue that if you've got a lot of file handling logic that you may want to unit test a handler rather than use integration testing... but I can envision some scenarios where it would be good to test with these. 

If you'll send along a PR with some tests, we'll bring it in.
