### ISSUE TITLE
Support phpunit 5

### ISSUE THREAD

**Issue by khrizt** [there4/slim-test-helpers#29]
Hi,

I'm upgrading to php 7 in my slim project and my unit testing can't work with scalar type hinting and returning types because that's only supported in phpunit 5.*

Is there a possibility to migrate and support phpunit 5.*?

Thanks

**Comment by craig-davis** [comment]
Hi, 

Thanks for checkout out this project. Currently, we're pinned to PhpUnit 4.*. I don't personally have time to investigate this change, but I would welcome a PR or new contributor to work on this. 

If you've got some time, this would probably be a welcome contribution. 

Sidenote - because this project is about unit testing Slim2, and we haven't address Slim3, I do somewhat consider this project to no longer be under active development.

**Comment by khrizt** [comment]
I'll take a look, any particular reason for being pinned to phpunit 4.*? So I have something to start investigating

**Comment by craig-davis** [comment]
> any particular reason
This project predates the release of PHPUnit 5, and I never found the new feature set compelling enough to upgrade. But, it would be a welcome addition!

**Comment by khrizt** [comment]
I've cloned the project, updated dependencies of both phpunit (to 5.*) and dbunit (to 2.*) and the tests pass OK. Also I've forked you library and added in my project, also my unit tests passed too. Is there anything else that I should try? If not I can make a PR

**Comment by craig-davis** [comment]
That sounds very thorough, and exciting. Make a PR and let's it going!

**Comment by khrizt** [comment]
I've made the PR [#30](https://github.com/there4/slim-test-helpers/pull/30) but looks like php version inferior to 5.6 should be deprecated because phpunit 5 only support 5.6+. What do you think?

**Comment by craig-davis** [comment]
This has made it to the new V3 master branch:
https://github.com/there4/slim-test-helpers/blob/master/composer.json#L24
